name: Unit Tests
run-name: ${{ github.actor }} is running GitHub Actions
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Build the dev container
        run: |
          cd ./_docker && ./build.sh && cd ..
          docker run  -d --name baffs-dev --privileged=true  -v /tmp/docker:/var/lib/docker  -v $PWD:/home/ubuntu/repos/BAFFS -v /home/ubuntu/.ssh/:/home/ubuntu/.ssh/   baffs-dev
      - name: Run Unit Tests
        run: docker exec -i baffs-dev make test
